from django.urls import path
from .views import *


urlpatterns = [
    path('login/',login,name='login'),
    path('register/',register,name='register'),
    path('room_type/',roomTypeView,name='roomType'),
    path('room_type/<pk>',roomTypeDetailView,name='roomTypeDetail'),
    path('room/',RoomAPIView.as_view(),name='roomapi'),
    path('customer/',CustomerView,name='customer'),
    path('customer/<pk>',CustomerDetailView,name='customerDetail'),
    path('cust/',CustomerAPIView.as_view(),name='customerapi'),
    path('bill/',BillView,name='bill'),
    path('bill/<pk>',BillDetailView,name='billDetail'),
    path('bills/',BillAPIView.as_view(),name='billapi'),
    path('payment/',PaymentInfoView,name='payment'),
    path('payment/<pk>',PaymentInfoDetailView,name='paymentDetail'),
    path('pay/',PaymentAPIView.as_view(),name='paymentapi'),
    path('employee/',EmployeeInfoView,name='employee'),
    path('employee/<pk>',EmployeeInfoDetailView,name='employeeDetail'),
    path('emp/',EmployeeAPIView.as_view(),name='employeeapi'),
    path('menuType/',MenuTypeView,name='menuType'),
    path('menuType/<pk>',MenuTypeDetailView,name='menuTypeDetail'),
    path('menu/',MenuTypeAPIView.as_view(),name='menuapi'),
    path('food/',FoodView,name='food'),
    path('food/<pk>',FoodDetailView,name='foodDetail'),
    path('foodapi/',FoodAPIView.as_view(),name='foodapi'),
    path('service/',ServiceView,name='service'),
    path('service/<pk>',ServiceDetailView,name='serviceDetail'),
    path('serviceapi/',ServiceAPIView.as_view(),name='serviceapi'),
    path('facilities/',FacilitiesView,name='facilities'),
    path('facilities/<pk>',FacilitiesDetailView,name='facilitiesDetail'),
    path('facilitiesapi/',FacilitiesAPIView.as_view(),name='facilitiesapi'),
]